name: Generate Datas

on:
  schedule: # execute every 12 hours
    - cron: "0 */5 * * *"
  workflow_dispatch:

jobs:
  build:
    name: Jobs to update datas
    runs-on: ubuntu-latest
    steps:
      # Snake Animation (Repositório que será utilizado para gerar os commits)
      - uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: ${{ github.lucasptcastro }}
          svg_out_path: dist/github-contribution-grid-snake.svg
          outputs: 
            dist/ocean.gif?color_snake=orange&color_dots=#bfd6f6,#8dbdff,#64a1f4,#4b91f1,#3c7dd9

      - uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
